//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
namespace PitchesAndNotes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string Name { get; set; }
        public int Grade { get; set; }
        public string Major { get; set; }
        [Display(Name = "Are you a Pitch or a Note?")]
        public string Classification { get; set; }
        [Display(Name = "What's On Your Bucket List?")]
        public string BucketList { get; set; }
        public int Id { get; set; }
    }
}
